services:
  database:
    image: postgres:17
    container_name: home_database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: me_salva_database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
